### ISSUE TITLE
Update the release process to ensure that project that require java 11 are built with java 11

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/OpenHFT#131]
I believe our release process uses java 8, however, we are starting to create some projects that now require java 11

![image](https://user-images.githubusercontent.com/6506056/169350869-534a2ba0-e512-4844-9972-7f5844bbe1db.png)

and include the module system

![image](https://user-images.githubusercontent.com/6506056/169350971-99d0ccf7-d21e-4181-adc1-d104f9012934.png)

**Comment by minborg** [comment]
Maybe there is a clever way to flag these projects.

**Comment by alamar** [comment]
I have pushed the first phase of changes governing such projects, driven by `Trait.JAVA_11`

Please take a look - @minborg can you please make crypto adapters Java 11-only (I assume they aren't now) so that we can try if PRs, build-all and release work?

Since our auxiliary agents don't seem to have Java 11, I have excluded those. I suggest that we completely move Windows, Mac and ARM to Java 11 only. If there are projects which can't be built with Java 11 I suggest we either fix or drop those. What do you think? So the Java 11 will gradually become the default JVM, and Java 8 "the JVM which we test and release stuff with"

**Comment by alamar** [comment]
I also wonder if CHRONICLE_ALL would build. Maybe we should exclude crypto adapters from CHRONICLE_ALL (shaded)

**Comment by RobAustin** [comment]
> I have pushed the first phase of changes governing such projects, driven by `Trait.JAVA_11`
> 
> Please take a look - @minborg can you please make crypto adapters Java 11-only (I assume they aren't now) so that we can try if PRs, build-all and release work?
> 
> Since our auxiliary agents don't seem to have Java 11, I have excluded those. I suggest that we completely move Windows, Mac and ARM to Java 11 only. If there are projects which can't be built with Java 11 I suggest we either fix or drop those. What do you think? So the Java 11 will gradually become the default JVM, and Java 8 "the JVM which we test and release stuff with"

I would be careful, ( i remember in the past when we moved off java 7 ) we had issues building java 7 code with java8 JVM, although it would build the jars, it causes issues for our users when they tried to run this with the Java7 JVM, the point is here, I believe, that we should still continue to build our java 8 code with java8.  And only build the code that requires java 11 ( with java 11 )

**Comment by alamar** [comment]
We will definitely continue releasing our code with Java 8 @RobAustin 

But all the other stuff we can move to Java 11 by default.
